### ISSUE TITLE
Verify a specific theme not all themes

### ISSUE THREAD

**Issue by MohamedBadawy** [IshYoBoy/ishyoboy-purchase-verifier#1]
Hi , nice work , can the plugin verify a specific theme which the purchase code belong it not  verify all themes ? like this http://www.denoizzed.com/forum and http://support.goodlayers.com/forum .
thank you

**Comment by VlooMan** [comment]
Hey, currently it's made to verify the purchase during the registration process only. Therefore it verifies that you are a valid buyer and gives you full access to the whole forum. The DB structure however is ready to handle multiple keys, we're planning to add a workflow for adding a new key for a different theme, but since this is a side project and not that essential for us at the moment we'll get back to it once we get some spare time. You could contribute to the code if you wish. We would be more than happy! Our basic idea is to hook into the user settings page and create an admin option to display your registered purchases and to be able to enter the new one.

**Comment by MohamedBadawy** [comment]
ok thanks!
